// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: sentryflow_metrics.proto

package golang

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIClassifierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	API           []string               `protobuf:"bytes,1,rep,name=API,proto3" json:"API,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIClassifierRequest) Reset() {
	*x = APIClassifierRequest{}
	mi := &file_sentryflow_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIClassifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIClassifierRequest) ProtoMessage() {}

func (x *APIClassifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIClassifierRequest.ProtoReflect.Descriptor instead.
func (*APIClassifierRequest) Descriptor() ([]byte, []int) {
	return file_sentryflow_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *APIClassifierRequest) GetAPI() []string {
	if x != nil {
		return x.API
	}
	return nil
}

type APIClassifierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	APIs          map[string]uint64      `protobuf:"bytes,1,rep,name=APIs,proto3" json:"APIs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIClassifierResponse) Reset() {
	*x = APIClassifierResponse{}
	mi := &file_sentryflow_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIClassifierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIClassifierResponse) ProtoMessage() {}

func (x *APIClassifierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIClassifierResponse.ProtoReflect.Descriptor instead.
func (*APIClassifierResponse) Descriptor() ([]byte, []int) {
	return file_sentryflow_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *APIClassifierResponse) GetAPIs() map[string]uint64 {
	if x != nil {
		return x.APIs
	}
	return nil
}

var File_sentryflow_metrics_proto protoreflect.FileDescriptor

const file_sentryflow_metrics_proto_rawDesc = "" +
	"\n" +
	"\x18sentryflow_metrics.proto\x12\bprotobuf\"(\n" +
	"\x14APIClassifierRequest\x12\x10\n" +
	"\x03API\x18\x01 \x03(\tR\x03API\"\x8f\x01\n" +
	"\x15APIClassifierResponse\x12=\n" +
	"\x04APIs\x18\x01 \x03(\v2).protobuf.APIClassifierResponse.APIsEntryR\x04APIs\x1a7\n" +
	"\tAPIsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x012d\n" +
	"\rAPIClassifier\x12S\n" +
	"\fClassifyAPIs\x12\x1e.protobuf.APIClassifierRequest\x1a\x1f.protobuf.APIClassifierResponse(\x010\x01B5Z3github.com/charankamal20/SentryFlow/protobuf/golangb\x06proto3"

var (
	file_sentryflow_metrics_proto_rawDescOnce sync.Once
	file_sentryflow_metrics_proto_rawDescData []byte
)

func file_sentryflow_metrics_proto_rawDescGZIP() []byte {
	file_sentryflow_metrics_proto_rawDescOnce.Do(func() {
		file_sentryflow_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentryflow_metrics_proto_rawDesc), len(file_sentryflow_metrics_proto_rawDesc)))
	})
	return file_sentryflow_metrics_proto_rawDescData
}

var file_sentryflow_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sentryflow_metrics_proto_goTypes = []any{
	(*APIClassifierRequest)(nil),  // 0: protobuf.APIClassifierRequest
	(*APIClassifierResponse)(nil), // 1: protobuf.APIClassifierResponse
	nil,                           // 2: protobuf.APIClassifierResponse.APIsEntry
}
var file_sentryflow_metrics_proto_depIdxs = []int32{
	2, // 0: protobuf.APIClassifierResponse.APIs:type_name -> protobuf.APIClassifierResponse.APIsEntry
	0, // 1: protobuf.APIClassifier.ClassifyAPIs:input_type -> protobuf.APIClassifierRequest
	1, // 2: protobuf.APIClassifier.ClassifyAPIs:output_type -> protobuf.APIClassifierResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sentryflow_metrics_proto_init() }
func file_sentryflow_metrics_proto_init() {
	if File_sentryflow_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentryflow_metrics_proto_rawDesc), len(file_sentryflow_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sentryflow_metrics_proto_goTypes,
		DependencyIndexes: file_sentryflow_metrics_proto_depIdxs,
		MessageInfos:      file_sentryflow_metrics_proto_msgTypes,
	}.Build()
	File_sentryflow_metrics_proto = out.File
	file_sentryflow_metrics_proto_goTypes = nil
	file_sentryflow_metrics_proto_depIdxs = nil
}
