// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: sentryflow.proto

package golang

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostName      string                 `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	IPAddress     string                 `protobuf:"bytes,2,opt,name=IPAddress,proto3" json:"IPAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_sentryflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{0}
}

func (x *ClientInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *ClientInfo) GetIPAddress() string {
	if x != nil {
		return x.IPAddress
	}
	return ""
}

// Deprecated: Marked as deprecated in sentryflow.proto.
type APILog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TimeStamp     string                 `protobuf:"bytes,2,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	SrcNamespace  string                 `protobuf:"bytes,11,opt,name=srcNamespace,proto3" json:"srcNamespace,omitempty"`
	SrcName       string                 `protobuf:"bytes,12,opt,name=srcName,proto3" json:"srcName,omitempty"`
	SrcLabel      map[string]string      `protobuf:"bytes,13,rep,name=srcLabel,proto3" json:"srcLabel,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SrcType       string                 `protobuf:"bytes,21,opt,name=srcType,proto3" json:"srcType,omitempty"`
	SrcIP         string                 `protobuf:"bytes,22,opt,name=srcIP,proto3" json:"srcIP,omitempty"`
	SrcPort       string                 `protobuf:"bytes,23,opt,name=srcPort,proto3" json:"srcPort,omitempty"`
	DstNamespace  string                 `protobuf:"bytes,31,opt,name=dstNamespace,proto3" json:"dstNamespace,omitempty"`
	DstName       string                 `protobuf:"bytes,32,opt,name=dstName,proto3" json:"dstName,omitempty"`
	DstLabel      map[string]string      `protobuf:"bytes,33,rep,name=dstLabel,proto3" json:"dstLabel,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DstType       string                 `protobuf:"bytes,41,opt,name=dstType,proto3" json:"dstType,omitempty"`
	DstIP         string                 `protobuf:"bytes,42,opt,name=dstIP,proto3" json:"dstIP,omitempty"`
	DstPort       string                 `protobuf:"bytes,43,opt,name=dstPort,proto3" json:"dstPort,omitempty"`
	Protocol      string                 `protobuf:"bytes,51,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Method        string                 `protobuf:"bytes,52,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,53,opt,name=path,proto3" json:"path,omitempty"`
	ResponseCode  int32                  `protobuf:"varint,54,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APILog) Reset() {
	*x = APILog{}
	mi := &file_sentryflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APILog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APILog) ProtoMessage() {}

func (x *APILog) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APILog.ProtoReflect.Descriptor instead.
func (*APILog) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{1}
}

func (x *APILog) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *APILog) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

func (x *APILog) GetSrcNamespace() string {
	if x != nil {
		return x.SrcNamespace
	}
	return ""
}

func (x *APILog) GetSrcName() string {
	if x != nil {
		return x.SrcName
	}
	return ""
}

func (x *APILog) GetSrcLabel() map[string]string {
	if x != nil {
		return x.SrcLabel
	}
	return nil
}

func (x *APILog) GetSrcType() string {
	if x != nil {
		return x.SrcType
	}
	return ""
}

func (x *APILog) GetSrcIP() string {
	if x != nil {
		return x.SrcIP
	}
	return ""
}

func (x *APILog) GetSrcPort() string {
	if x != nil {
		return x.SrcPort
	}
	return ""
}

func (x *APILog) GetDstNamespace() string {
	if x != nil {
		return x.DstNamespace
	}
	return ""
}

func (x *APILog) GetDstName() string {
	if x != nil {
		return x.DstName
	}
	return ""
}

func (x *APILog) GetDstLabel() map[string]string {
	if x != nil {
		return x.DstLabel
	}
	return nil
}

func (x *APILog) GetDstType() string {
	if x != nil {
		return x.DstType
	}
	return ""
}

func (x *APILog) GetDstIP() string {
	if x != nil {
		return x.DstIP
	}
	return ""
}

func (x *APILog) GetDstPort() string {
	if x != nil {
		return x.DstPort
	}
	return ""
}

func (x *APILog) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *APILog) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *APILog) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *APILog) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

// APIEvent represents an event related to an API call, including metadata,
// source and destination workloads, and network information.
type APIEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Metadata    *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Source      *Workload              `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Destination *Workload              `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	// Types that are valid to be assigned to Req:
	//
	//	*APIEvent_Request
	//	*APIEvent_DnsRequest
	Req isAPIEvent_Req `protobuf_oneof:"req"`
	// Types that are valid to be assigned to Res:
	//
	//	*APIEvent_Response
	//	*APIEvent_DnsResponse
	Res      isAPIEvent_Res `protobuf_oneof:"res"`
	Protocol string         `protobuf:"bytes,7,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// End-to-end observed latency in milliseconds.
	LatencyMs     uint32 `protobuf:"varint,8,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIEvent) Reset() {
	*x = APIEvent{}
	mi := &file_sentryflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIEvent) ProtoMessage() {}

func (x *APIEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIEvent.ProtoReflect.Descriptor instead.
func (*APIEvent) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{2}
}

func (x *APIEvent) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *APIEvent) GetSource() *Workload {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *APIEvent) GetDestination() *Workload {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *APIEvent) GetReq() isAPIEvent_Req {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *APIEvent) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Req.(*APIEvent_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *APIEvent) GetDnsRequest() *DNSRequest {
	if x != nil {
		if x, ok := x.Req.(*APIEvent_DnsRequest); ok {
			return x.DnsRequest
		}
	}
	return nil
}

func (x *APIEvent) GetRes() isAPIEvent_Res {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *APIEvent) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Res.(*APIEvent_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *APIEvent) GetDnsResponse() *DNSResponse {
	if x != nil {
		if x, ok := x.Res.(*APIEvent_DnsResponse); ok {
			return x.DnsResponse
		}
	}
	return nil
}

func (x *APIEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *APIEvent) GetLatencyMs() uint32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type isAPIEvent_Req interface {
	isAPIEvent_Req()
}

type APIEvent_Request struct {
	Request *Request `protobuf:"bytes,5,opt,name=request,proto3,oneof"`
}

type APIEvent_DnsRequest struct {
	DnsRequest *DNSRequest `protobuf:"bytes,9,opt,name=dns_request,json=dnsRequest,proto3,oneof"`
}

func (*APIEvent_Request) isAPIEvent_Req() {}

func (*APIEvent_DnsRequest) isAPIEvent_Req() {}

type isAPIEvent_Res interface {
	isAPIEvent_Res()
}

type APIEvent_Response struct {
	Response *Response `protobuf:"bytes,6,opt,name=response,proto3,oneof"`
}

type APIEvent_DnsResponse struct {
	DnsResponse *DNSResponse `protobuf:"bytes,10,opt,name=dns_response,json=dnsResponse,proto3,oneof"`
}

func (*APIEvent_Response) isAPIEvent_Res() {}

func (*APIEvent_DnsResponse) isAPIEvent_Res() {}

type Metadata struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ContextId uint32                 `protobuf:"varint,1,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Timestamp uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Deprecated: Marked as deprecated in sentryflow.proto.
	IstioVersion string `protobuf:"bytes,3,opt,name=istio_version,json=istioVersion,proto3" json:"istio_version,omitempty"`
	MeshId       string `protobuf:"bytes,4,opt,name=mesh_id,json=meshId,proto3" json:"mesh_id,omitempty"`
	// The name of the Kubernetes node where the workload is running. If the workload
	// is not running in a Kubernetes environment, this field will be empty.
	NodeName string `protobuf:"bytes,5,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Name of receiver (e.g., Istio, nginx).
	ReceiverName string `protobuf:"bytes,6,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	// Version of receiver (e.g., 1.26.2).
	ReceiverVersion string `protobuf:"bytes,7,opt,name=receiver_version,json=receiverVersion,proto3" json:"receiver_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_sentryflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{3}
}

func (x *Metadata) GetContextId() uint32 {
	if x != nil {
		return x.ContextId
	}
	return 0
}

func (x *Metadata) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Deprecated: Marked as deprecated in sentryflow.proto.
func (x *Metadata) GetIstioVersion() string {
	if x != nil {
		return x.IstioVersion
	}
	return ""
}

func (x *Metadata) GetMeshId() string {
	if x != nil {
		return x.MeshId
	}
	return ""
}

func (x *Metadata) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Metadata) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *Metadata) GetReceiverVersion() string {
	if x != nil {
		return x.ReceiverVersion
	}
	return ""
}

// Workload represents a generic entity that can be either a Kubernetes or
// non-Kubernetes resource. It serves as a source or destination for access
// within a system.
type Workload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the workload.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The namespace in which the workload is deployed. This field is only applicable
	// for Kubernetes workloads.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// The IP address of the workload.
	Ip string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	// The port number used by the workload.
	Port int32 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// K8s labels for policy matching.
	Labels map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Workload kind: "Pod", "Service", or "External".
	Kind          string `protobuf:"bytes,6,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_sentryflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{4}
}

func (x *Workload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workload) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Workload) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Workload) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Workload) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Workload) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// Request represents an incoming HTTP request.
type Request struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Headers map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body    string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// HTTP method (GET, POST, etc.) or gRPC method name.
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// URL path or gRPC full method path (e.g. /pkg.Svc/Method).
	Path string `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	// gRPC service name (e.g. "helloworld.Greeter")
	GrpcService string `protobuf:"bytes,5,opt,name=grpc_service,json=grpcService,proto3" json:"grpc_service,omitempty"`
	// gRPC method name (e.g. "SayHello")
	GrpcMethod string `protobuf:"bytes,6,opt,name=grpc_method,json=grpcMethod,proto3" json:"grpc_method,omitempty"`
	// Content-Type header value (e.g. "application/grpc")
	ContentType   string `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_sentryflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{5}
}

func (x *Request) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Request) GetGrpcService() string {
	if x != nil {
		return x.GrpcService
	}
	return ""
}

func (x *Request) GetGrpcMethod() string {
	if x != nil {
		return x.GrpcMethod
	}
	return ""
}

func (x *Request) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// Response represents an outgoing HTTP response.
type Response struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Headers               map[string]string      `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body                  string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	BackendLatencyInNanos uint64                 `protobuf:"varint,3,opt,name=backend_latency_in_nanos,json=backendLatencyInNanos,proto3" json:"backend_latency_in_nanos,omitempty"`
	// HTTP status code or gRPC status code.
	StatusCode int32 `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// gRPC status code (0=OK, 1=CANCELLED, 2=UNKNOWN, etc.)
	GrpcStatusCode int32 `protobuf:"varint,5,opt,name=grpc_status_code,json=grpcStatusCode,proto3" json:"grpc_status_code,omitempty"`
	// Human-readable gRPC error message from grpc-message trailer.
	GrpcStatusMessage string `protobuf:"bytes,6,opt,name=grpc_status_message,json=grpcStatusMessage,proto3" json:"grpc_status_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_sentryflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{6}
}

func (x *Response) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Response) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Response) GetBackendLatencyInNanos() uint64 {
	if x != nil {
		return x.BackendLatencyInNanos
	}
	return 0
}

func (x *Response) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Response) GetGrpcStatusCode() int32 {
	if x != nil {
		return x.GrpcStatusCode
	}
	return 0
}

func (x *Response) GetGrpcStatusMessage() string {
	if x != nil {
		return x.GrpcStatusMessage
	}
	return ""
}

type DNSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryName     string                 `protobuf:"bytes,1,opt,name=query_name,json=queryName,proto3" json:"query_name,omitempty"`
	QueryType     string                 `protobuf:"bytes,2,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"` // e.g., "A", "AAAA"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRequest) Reset() {
	*x = DNSRequest{}
	mi := &file_sentryflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRequest) ProtoMessage() {}

func (x *DNSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRequest.ProtoReflect.Descriptor instead.
func (*DNSRequest) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{7}
}

func (x *DNSRequest) GetQueryName() string {
	if x != nil {
		return x.QueryName
	}
	return ""
}

func (x *DNSRequest) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

type DNSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rcode         int32                  `protobuf:"varint,1,opt,name=rcode,proto3" json:"rcode,omitempty"`                         // 0 for NoError, 3 for NXDomain
	RcodeName     string                 `protobuf:"bytes,2,opt,name=rcode_name,json=rcodeName,proto3" json:"rcode_name,omitempty"` // e.g. "NoError"
	ResolvedIps   []string               `protobuf:"bytes,3,rep,name=resolved_ips,json=resolvedIps,proto3" json:"resolved_ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSResponse) Reset() {
	*x = DNSResponse{}
	mi := &file_sentryflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSResponse) ProtoMessage() {}

func (x *DNSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSResponse.ProtoReflect.Descriptor instead.
func (*DNSResponse) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{8}
}

func (x *DNSResponse) GetRcode() int32 {
	if x != nil {
		return x.Rcode
	}
	return 0
}

func (x *DNSResponse) GetRcodeName() string {
	if x != nil {
		return x.RcodeName
	}
	return ""
}

func (x *DNSResponse) GetResolvedIps() []string {
	if x != nil {
		return x.ResolvedIps
	}
	return nil
}

type APIMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PerAPICounts  map[string]uint64      `protobuf:"bytes,1,rep,name=perAPICounts,proto3" json:"perAPICounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // @todo: add some more metrics here
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIMetrics) Reset() {
	*x = APIMetrics{}
	mi := &file_sentryflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIMetrics) ProtoMessage() {}

func (x *APIMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIMetrics.ProtoReflect.Descriptor instead.
func (*APIMetrics) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{9}
}

func (x *APIMetrics) GetPerAPICounts() map[string]uint64 {
	if x != nil {
		return x.PerAPICounts
	}
	return nil
}

type MetricValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         map[string]string      `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricValue) Reset() {
	*x = MetricValue{}
	mi := &file_sentryflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricValue) ProtoMessage() {}

func (x *MetricValue) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricValue.ProtoReflect.Descriptor instead.
func (*MetricValue) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{10}
}

func (x *MetricValue) GetValue() map[string]string {
	if x != nil {
		return x.Value
	}
	return nil
}

type EnvoyMetrics struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TimeStamp     string                  `protobuf:"bytes,1,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Namespace     string                  `protobuf:"bytes,11,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                  `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	IPAddress     string                  `protobuf:"bytes,13,opt,name=IPAddress,proto3" json:"IPAddress,omitempty"`
	Labels        map[string]string       `protobuf:"bytes,14,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metrics       map[string]*MetricValue `protobuf:"bytes,21,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvoyMetrics) Reset() {
	*x = EnvoyMetrics{}
	mi := &file_sentryflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvoyMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvoyMetrics) ProtoMessage() {}

func (x *EnvoyMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvoyMetrics.ProtoReflect.Descriptor instead.
func (*EnvoyMetrics) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{11}
}

func (x *EnvoyMetrics) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

func (x *EnvoyMetrics) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *EnvoyMetrics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvoyMetrics) GetIPAddress() string {
	if x != nil {
		return x.IPAddress
	}
	return ""
}

func (x *EnvoyMetrics) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *EnvoyMetrics) GetMetrics() map[string]*MetricValue {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// APIEventFilter controls which events are streamed to a subscriber.
type APIEventFilter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName        string                 `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Protocols      []string               `protobuf:"bytes,3,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Methods        []string               `protobuf:"bytes,4,rep,name=methods,proto3" json:"methods,omitempty"`
	StatusPatterns []string               `protobuf:"bytes,5,rep,name=status_patterns,json=statusPatterns,proto3" json:"status_patterns,omitempty"`
	MinDurationMs  int64                  `protobuf:"varint,6,opt,name=min_duration_ms,json=minDurationMs,proto3" json:"min_duration_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *APIEventFilter) Reset() {
	*x = APIEventFilter{}
	mi := &file_sentryflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIEventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIEventFilter) ProtoMessage() {}

func (x *APIEventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIEventFilter.ProtoReflect.Descriptor instead.
func (*APIEventFilter) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{12}
}

func (x *APIEventFilter) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *APIEventFilter) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *APIEventFilter) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *APIEventFilter) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *APIEventFilter) GetStatusPatterns() []string {
	if x != nil {
		return x.StatusPatterns
	}
	return nil
}

func (x *APIEventFilter) GetMinDurationMs() int64 {
	if x != nil {
		return x.MinDurationMs
	}
	return 0
}

// MetricsRequest is the input for GetAPIMetrics.
type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_sentryflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{13}
}

// APIObserverMetrics provides aggregated API observability statistics.
type APIObserverMetrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Timestamp            string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TotalEvents          uint64                 `protobuf:"varint,2,opt,name=total_events,json=totalEvents,proto3" json:"total_events,omitempty"`
	EventsByProtocol     map[string]uint64      `protobuf:"bytes,3,rep,name=events_by_protocol,json=eventsByProtocol,proto3" json:"events_by_protocol,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	EventsByStatus       map[string]uint64      `protobuf:"bytes,4,rep,name=events_by_status,json=eventsByStatus,proto3" json:"events_by_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	TopEndpoints         []*EndpointMetric      `protobuf:"bytes,5,rep,name=top_endpoints,json=topEndpoints,proto3" json:"top_endpoints,omitempty"`
	AvgLatencyByEndpoint map[string]float64     `protobuf:"bytes,6,rep,name=avg_latency_by_endpoint,json=avgLatencyByEndpoint,proto3" json:"avg_latency_by_endpoint,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	ErrorRate            float64                `protobuf:"fixed64,7,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *APIObserverMetrics) Reset() {
	*x = APIObserverMetrics{}
	mi := &file_sentryflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIObserverMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIObserverMetrics) ProtoMessage() {}

func (x *APIObserverMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIObserverMetrics.ProtoReflect.Descriptor instead.
func (*APIObserverMetrics) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{14}
}

func (x *APIObserverMetrics) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *APIObserverMetrics) GetTotalEvents() uint64 {
	if x != nil {
		return x.TotalEvents
	}
	return 0
}

func (x *APIObserverMetrics) GetEventsByProtocol() map[string]uint64 {
	if x != nil {
		return x.EventsByProtocol
	}
	return nil
}

func (x *APIObserverMetrics) GetEventsByStatus() map[string]uint64 {
	if x != nil {
		return x.EventsByStatus
	}
	return nil
}

func (x *APIObserverMetrics) GetTopEndpoints() []*EndpointMetric {
	if x != nil {
		return x.TopEndpoints
	}
	return nil
}

func (x *APIObserverMetrics) GetAvgLatencyByEndpoint() map[string]float64 {
	if x != nil {
		return x.AvgLatencyByEndpoint
	}
	return nil
}

func (x *APIObserverMetrics) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

// EndpointMetric captures per-endpoint statistics.
type EndpointMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	RequestCount  uint64                 `protobuf:"varint,3,opt,name=request_count,json=requestCount,proto3" json:"request_count,omitempty"`
	AvgLatencyMs  float64                `protobuf:"fixed64,4,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	P95LatencyMs  float64                `protobuf:"fixed64,5,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	P99LatencyMs  float64                `protobuf:"fixed64,6,opt,name=p99_latency_ms,json=p99LatencyMs,proto3" json:"p99_latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointMetric) Reset() {
	*x = EndpointMetric{}
	mi := &file_sentryflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointMetric) ProtoMessage() {}

func (x *EndpointMetric) ProtoReflect() protoreflect.Message {
	mi := &file_sentryflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointMetric.ProtoReflect.Descriptor instead.
func (*EndpointMetric) Descriptor() ([]byte, []int) {
	return file_sentryflow_proto_rawDescGZIP(), []int{15}
}

func (x *EndpointMetric) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *EndpointMetric) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EndpointMetric) GetRequestCount() uint64 {
	if x != nil {
		return x.RequestCount
	}
	return 0
}

func (x *EndpointMetric) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *EndpointMetric) GetP95LatencyMs() float64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

func (x *EndpointMetric) GetP99LatencyMs() float64 {
	if x != nil {
		return x.P99LatencyMs
	}
	return 0
}

var File_sentryflow_proto protoreflect.FileDescriptor

const file_sentryflow_proto_rawDesc = "" +
	"\n" +
	"\x10sentryflow.proto\x12\bprotobuf\"F\n" +
	"\n" +
	"ClientInfo\x12\x1a\n" +
	"\bhostName\x18\x01 \x01(\tR\bhostName\x12\x1c\n" +
	"\tIPAddress\x18\x02 \x01(\tR\tIPAddress\"\xa8\x05\n" +
	"\x06APILog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\ttimeStamp\x18\x02 \x01(\tR\ttimeStamp\x12\"\n" +
	"\fsrcNamespace\x18\v \x01(\tR\fsrcNamespace\x12\x18\n" +
	"\asrcName\x18\f \x01(\tR\asrcName\x12:\n" +
	"\bsrcLabel\x18\r \x03(\v2\x1e.protobuf.APILog.SrcLabelEntryR\bsrcLabel\x12\x18\n" +
	"\asrcType\x18\x15 \x01(\tR\asrcType\x12\x14\n" +
	"\x05srcIP\x18\x16 \x01(\tR\x05srcIP\x12\x18\n" +
	"\asrcPort\x18\x17 \x01(\tR\asrcPort\x12\"\n" +
	"\fdstNamespace\x18\x1f \x01(\tR\fdstNamespace\x12\x18\n" +
	"\adstName\x18  \x01(\tR\adstName\x12:\n" +
	"\bdstLabel\x18! \x03(\v2\x1e.protobuf.APILog.DstLabelEntryR\bdstLabel\x12\x18\n" +
	"\adstType\x18) \x01(\tR\adstType\x12\x14\n" +
	"\x05dstIP\x18* \x01(\tR\x05dstIP\x12\x18\n" +
	"\adstPort\x18+ \x01(\tR\adstPort\x12\x1a\n" +
	"\bprotocol\x183 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06method\x184 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x185 \x01(\tR\x04path\x12\"\n" +
	"\fresponseCode\x186 \x01(\x05R\fresponseCode\x1a;\n" +
	"\rSrcLabelEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rDstLabelEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x02\x18\x01\"\xbb\x03\n" +
	"\bAPIEvent\x12.\n" +
	"\bmetadata\x18\x01 \x01(\v2\x12.protobuf.MetadataR\bmetadata\x12*\n" +
	"\x06source\x18\x03 \x01(\v2\x12.protobuf.WorkloadR\x06source\x124\n" +
	"\vdestination\x18\x04 \x01(\v2\x12.protobuf.WorkloadR\vdestination\x12-\n" +
	"\arequest\x18\x05 \x01(\v2\x11.protobuf.RequestH\x00R\arequest\x127\n" +
	"\vdns_request\x18\t \x01(\v2\x14.protobuf.DNSRequestH\x00R\n" +
	"dnsRequest\x120\n" +
	"\bresponse\x18\x06 \x01(\v2\x12.protobuf.ResponseH\x01R\bresponse\x12:\n" +
	"\fdns_response\x18\n" +
	" \x01(\v2\x15.protobuf.DNSResponseH\x01R\vdnsResponse\x12\x1a\n" +
	"\bprotocol\x18\a \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\b \x01(\rR\tlatencyMsB\x05\n" +
	"\x03reqB\x05\n" +
	"\x03res\"\xf6\x01\n" +
	"\bMetadata\x12\x1d\n" +
	"\n" +
	"context_id\x18\x01 \x01(\rR\tcontextId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12'\n" +
	"\ristio_version\x18\x03 \x01(\tB\x02\x18\x01R\fistioVersion\x12\x17\n" +
	"\amesh_id\x18\x04 \x01(\tR\x06meshId\x12\x1b\n" +
	"\tnode_name\x18\x05 \x01(\tR\bnodeName\x12#\n" +
	"\rreceiver_name\x18\x06 \x01(\tR\freceiverName\x12)\n" +
	"\x10receiver_version\x18\a \x01(\tR\x0freceiverVersion\"\xe7\x01\n" +
	"\bWorkload\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x126\n" +
	"\x06labels\x18\x05 \x03(\v2\x1e.protobuf.Workload.LabelsEntryR\x06labels\x12\x12\n" +
	"\x04kind\x18\x06 \x01(\tR\x04kind\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x02\n" +
	"\aRequest\x128\n" +
	"\aheaders\x18\x01 \x03(\v2\x1e.protobuf.Request.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12!\n" +
	"\fgrpc_service\x18\x05 \x01(\tR\vgrpcService\x12\x1f\n" +
	"\vgrpc_method\x18\x06 \x01(\tR\n" +
	"grpcMethod\x12!\n" +
	"\fcontent_type\x18\a \x01(\tR\vcontentType\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x02\n" +
	"\bResponse\x129\n" +
	"\aheaders\x18\x01 \x03(\v2\x1f.protobuf.Response.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x127\n" +
	"\x18backend_latency_in_nanos\x18\x03 \x01(\x04R\x15backendLatencyInNanos\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12(\n" +
	"\x10grpc_status_code\x18\x05 \x01(\x05R\x0egrpcStatusCode\x12.\n" +
	"\x13grpc_status_message\x18\x06 \x01(\tR\x11grpcStatusMessage\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"J\n" +
	"\n" +
	"DNSRequest\x12\x1d\n" +
	"\n" +
	"query_name\x18\x01 \x01(\tR\tqueryName\x12\x1d\n" +
	"\n" +
	"query_type\x18\x02 \x01(\tR\tqueryType\"e\n" +
	"\vDNSResponse\x12\x14\n" +
	"\x05rcode\x18\x01 \x01(\x05R\x05rcode\x12\x1d\n" +
	"\n" +
	"rcode_name\x18\x02 \x01(\tR\trcodeName\x12!\n" +
	"\fresolved_ips\x18\x03 \x03(\tR\vresolvedIps\"\x99\x01\n" +
	"\n" +
	"APIMetrics\x12J\n" +
	"\fperAPICounts\x18\x01 \x03(\v2&.protobuf.APIMetrics.PerAPICountsEntryR\fperAPICounts\x1a?\n" +
	"\x11PerAPICountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x7f\n" +
	"\vMetricValue\x126\n" +
	"\x05value\x18\x01 \x03(\v2 .protobuf.MetricValue.ValueEntryR\x05value\x1a8\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x85\x03\n" +
	"\fEnvoyMetrics\x12\x1c\n" +
	"\ttimeStamp\x18\x01 \x01(\tR\ttimeStamp\x12\x1c\n" +
	"\tnamespace\x18\v \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\f \x01(\tR\x04name\x12\x1c\n" +
	"\tIPAddress\x18\r \x01(\tR\tIPAddress\x12:\n" +
	"\x06labels\x18\x0e \x03(\v2\".protobuf.EnvoyMetrics.LabelsEntryR\x06labels\x12=\n" +
	"\ametrics\x18\x15 \x03(\v2#.protobuf.EnvoyMetrics.MetricsEntryR\ametrics\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aQ\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.protobuf.MetricValueR\x05value:\x028\x01\"\xd2\x01\n" +
	"\x0eAPIEventFilter\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12\x1c\n" +
	"\tprotocols\x18\x03 \x03(\tR\tprotocols\x12\x18\n" +
	"\amethods\x18\x04 \x03(\tR\amethods\x12'\n" +
	"\x0fstatus_patterns\x18\x05 \x03(\tR\x0estatusPatterns\x12&\n" +
	"\x0fmin_duration_ms\x18\x06 \x01(\x03R\rminDurationMs\"\x10\n" +
	"\x0eMetricsRequest\"\xb1\x05\n" +
	"\x12APIObserverMetrics\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12!\n" +
	"\ftotal_events\x18\x02 \x01(\x04R\vtotalEvents\x12`\n" +
	"\x12events_by_protocol\x18\x03 \x03(\v22.protobuf.APIObserverMetrics.EventsByProtocolEntryR\x10eventsByProtocol\x12Z\n" +
	"\x10events_by_status\x18\x04 \x03(\v20.protobuf.APIObserverMetrics.EventsByStatusEntryR\x0eeventsByStatus\x12=\n" +
	"\rtop_endpoints\x18\x05 \x03(\v2\x18.protobuf.EndpointMetricR\ftopEndpoints\x12m\n" +
	"\x17avg_latency_by_endpoint\x18\x06 \x03(\v26.protobuf.APIObserverMetrics.AvgLatencyByEndpointEntryR\x14avgLatencyByEndpoint\x12\x1d\n" +
	"\n" +
	"error_rate\x18\a \x01(\x01R\terrorRate\x1aC\n" +
	"\x15EventsByProtocolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aA\n" +
	"\x13EventsByStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aG\n" +
	"\x19AvgLatencyByEndpointEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xd3\x01\n" +
	"\x0eEndpointMetric\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12#\n" +
	"\rrequest_count\x18\x03 \x01(\x04R\frequestCount\x12$\n" +
	"\x0eavg_latency_ms\x18\x04 \x01(\x01R\favgLatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x05 \x01(\x01R\fp95LatencyMs\x12$\n" +
	"\x0ep99_latency_ms\x18\x06 \x01(\x01R\fp99LatencyMs2\xbd\x02\n" +
	"\n" +
	"SentryFlow\x12:\n" +
	"\tGetAPILog\x12\x14.protobuf.ClientInfo\x1a\x10.protobuf.APILog\"\x03\x88\x02\x010\x01\x129\n" +
	"\vGetAPIEvent\x12\x14.protobuf.ClientInfo\x1a\x12.protobuf.APIEvent0\x01\x126\n" +
	"\fSendAPIEvent\x12\x12.protobuf.APIEvent\x1a\x12.protobuf.APIEvent\x12=\n" +
	"\rGetAPIMetrics\x12\x14.protobuf.ClientInfo\x1a\x14.protobuf.APIMetrics0\x01\x12A\n" +
	"\x0fGetEnvoyMetrics\x12\x14.protobuf.ClientInfo\x1a\x16.protobuf.EnvoyMetrics0\x012\x9d\x01\n" +
	"\x12APIObserverService\x12>\n" +
	"\fGetAPIEvents\x12\x18.protobuf.APIEventFilter\x1a\x12.protobuf.APIEvent0\x01\x12G\n" +
	"\rGetAPIMetrics\x12\x18.protobuf.MetricsRequest\x1a\x1c.protobuf.APIObserverMetricsB0Z.github.com/accuknox/SentryFlow/protobuf/golangb\x06proto3"

var (
	file_sentryflow_proto_rawDescOnce sync.Once
	file_sentryflow_proto_rawDescData []byte
)

func file_sentryflow_proto_rawDescGZIP() []byte {
	file_sentryflow_proto_rawDescOnce.Do(func() {
		file_sentryflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sentryflow_proto_rawDesc), len(file_sentryflow_proto_rawDesc)))
	})
	return file_sentryflow_proto_rawDescData
}

var file_sentryflow_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_sentryflow_proto_goTypes = []any{
	(*ClientInfo)(nil),         // 0: protobuf.ClientInfo
	(*APILog)(nil),             // 1: protobuf.APILog
	(*APIEvent)(nil),           // 2: protobuf.APIEvent
	(*Metadata)(nil),           // 3: protobuf.Metadata
	(*Workload)(nil),           // 4: protobuf.Workload
	(*Request)(nil),            // 5: protobuf.Request
	(*Response)(nil),           // 6: protobuf.Response
	(*DNSRequest)(nil),         // 7: protobuf.DNSRequest
	(*DNSResponse)(nil),        // 8: protobuf.DNSResponse
	(*APIMetrics)(nil),         // 9: protobuf.APIMetrics
	(*MetricValue)(nil),        // 10: protobuf.MetricValue
	(*EnvoyMetrics)(nil),       // 11: protobuf.EnvoyMetrics
	(*APIEventFilter)(nil),     // 12: protobuf.APIEventFilter
	(*MetricsRequest)(nil),     // 13: protobuf.MetricsRequest
	(*APIObserverMetrics)(nil), // 14: protobuf.APIObserverMetrics
	(*EndpointMetric)(nil),     // 15: protobuf.EndpointMetric
	nil,                        // 16: protobuf.APILog.SrcLabelEntry
	nil,                        // 17: protobuf.APILog.DstLabelEntry
	nil,                        // 18: protobuf.Workload.LabelsEntry
	nil,                        // 19: protobuf.Request.HeadersEntry
	nil,                        // 20: protobuf.Response.HeadersEntry
	nil,                        // 21: protobuf.APIMetrics.PerAPICountsEntry
	nil,                        // 22: protobuf.MetricValue.ValueEntry
	nil,                        // 23: protobuf.EnvoyMetrics.LabelsEntry
	nil,                        // 24: protobuf.EnvoyMetrics.MetricsEntry
	nil,                        // 25: protobuf.APIObserverMetrics.EventsByProtocolEntry
	nil,                        // 26: protobuf.APIObserverMetrics.EventsByStatusEntry
	nil,                        // 27: protobuf.APIObserverMetrics.AvgLatencyByEndpointEntry
}
var file_sentryflow_proto_depIdxs = []int32{
	16, // 0: protobuf.APILog.srcLabel:type_name -> protobuf.APILog.SrcLabelEntry
	17, // 1: protobuf.APILog.dstLabel:type_name -> protobuf.APILog.DstLabelEntry
	3,  // 2: protobuf.APIEvent.metadata:type_name -> protobuf.Metadata
	4,  // 3: protobuf.APIEvent.source:type_name -> protobuf.Workload
	4,  // 4: protobuf.APIEvent.destination:type_name -> protobuf.Workload
	5,  // 5: protobuf.APIEvent.request:type_name -> protobuf.Request
	7,  // 6: protobuf.APIEvent.dns_request:type_name -> protobuf.DNSRequest
	6,  // 7: protobuf.APIEvent.response:type_name -> protobuf.Response
	8,  // 8: protobuf.APIEvent.dns_response:type_name -> protobuf.DNSResponse
	18, // 9: protobuf.Workload.labels:type_name -> protobuf.Workload.LabelsEntry
	19, // 10: protobuf.Request.headers:type_name -> protobuf.Request.HeadersEntry
	20, // 11: protobuf.Response.headers:type_name -> protobuf.Response.HeadersEntry
	21, // 12: protobuf.APIMetrics.perAPICounts:type_name -> protobuf.APIMetrics.PerAPICountsEntry
	22, // 13: protobuf.MetricValue.value:type_name -> protobuf.MetricValue.ValueEntry
	23, // 14: protobuf.EnvoyMetrics.labels:type_name -> protobuf.EnvoyMetrics.LabelsEntry
	24, // 15: protobuf.EnvoyMetrics.metrics:type_name -> protobuf.EnvoyMetrics.MetricsEntry
	25, // 16: protobuf.APIObserverMetrics.events_by_protocol:type_name -> protobuf.APIObserverMetrics.EventsByProtocolEntry
	26, // 17: protobuf.APIObserverMetrics.events_by_status:type_name -> protobuf.APIObserverMetrics.EventsByStatusEntry
	15, // 18: protobuf.APIObserverMetrics.top_endpoints:type_name -> protobuf.EndpointMetric
	27, // 19: protobuf.APIObserverMetrics.avg_latency_by_endpoint:type_name -> protobuf.APIObserverMetrics.AvgLatencyByEndpointEntry
	10, // 20: protobuf.EnvoyMetrics.MetricsEntry.value:type_name -> protobuf.MetricValue
	0,  // 21: protobuf.SentryFlow.GetAPILog:input_type -> protobuf.ClientInfo
	0,  // 22: protobuf.SentryFlow.GetAPIEvent:input_type -> protobuf.ClientInfo
	2,  // 23: protobuf.SentryFlow.SendAPIEvent:input_type -> protobuf.APIEvent
	0,  // 24: protobuf.SentryFlow.GetAPIMetrics:input_type -> protobuf.ClientInfo
	0,  // 25: protobuf.SentryFlow.GetEnvoyMetrics:input_type -> protobuf.ClientInfo
	12, // 26: protobuf.APIObserverService.GetAPIEvents:input_type -> protobuf.APIEventFilter
	13, // 27: protobuf.APIObserverService.GetAPIMetrics:input_type -> protobuf.MetricsRequest
	1,  // 28: protobuf.SentryFlow.GetAPILog:output_type -> protobuf.APILog
	2,  // 29: protobuf.SentryFlow.GetAPIEvent:output_type -> protobuf.APIEvent
	2,  // 30: protobuf.SentryFlow.SendAPIEvent:output_type -> protobuf.APIEvent
	9,  // 31: protobuf.SentryFlow.GetAPIMetrics:output_type -> protobuf.APIMetrics
	11, // 32: protobuf.SentryFlow.GetEnvoyMetrics:output_type -> protobuf.EnvoyMetrics
	2,  // 33: protobuf.APIObserverService.GetAPIEvents:output_type -> protobuf.APIEvent
	14, // 34: protobuf.APIObserverService.GetAPIMetrics:output_type -> protobuf.APIObserverMetrics
	28, // [28:35] is the sub-list for method output_type
	21, // [21:28] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_sentryflow_proto_init() }
func file_sentryflow_proto_init() {
	if File_sentryflow_proto != nil {
		return
	}
	file_sentryflow_proto_msgTypes[2].OneofWrappers = []any{
		(*APIEvent_Request)(nil),
		(*APIEvent_DnsRequest)(nil),
		(*APIEvent_Response)(nil),
		(*APIEvent_DnsResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sentryflow_proto_rawDesc), len(file_sentryflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_sentryflow_proto_goTypes,
		DependencyIndexes: file_sentryflow_proto_depIdxs,
		MessageInfos:      file_sentryflow_proto_msgTypes,
	}.Build()
	File_sentryflow_proto = out.File
	file_sentryflow_proto_goTypes = nil
	file_sentryflow_proto_depIdxs = nil
}
