filters:
  server:
    port: 8081
  envoy:
    uri: classikh/sentryflow-httpfilter
    gatewayTag: "latest-gateway"
    sidecarTag: "latest-sidecar"

receivers:
  serviceMeshes:
    - name: istio-gateway
      namespace: istio-system
    - name: istio-sidecar
      namespace: istio-system

exporter:
  grpc:
    port: 8080
